# Generated by Django 6.0.4 on 2026-04-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=50)),
                ('family_id', models.CharField(db_index=True, default='Not Set', max_length=50)),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(db_index=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
                ('intimation_raised_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CGHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=50)),
                ('family_id', models.CharField(db_index=True, default='Not Set', max_length=50)),
                ('case_id', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_name', models.CharField(db_index=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
                ('intimation_raised_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=50)),
                ('service_number', models.CharField(db_index=True, default='Not Set', max_length=50)),
                ('patient_name', models.CharField(db_index=True, max_length=100)),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Discharge Date')),
                ('claim_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('io', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stay', models.IntegerField(blank=True, null=True)),
                ('ailment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
